# CONFIGURAÇÃO DO BANCO DE DADOS (POSTGRESQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/kesslervision
spring.datasource.username=postgres
spring.datasource.password=1234

# CONFIGURAÇÕES DO JPA / HIBERNATE (Cria as tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostra os comandos SQL no terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true